I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 172, in script call
    call expression "splashscreen" from _call_splashscreen_1
  File "game/script.rpy", line 84, in script
    spouse "[player_name], I… I can’t. We can’t. I’m leaving you."
KeyError: 'spousename'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 172, in script call
    call expression "splashscreen" from _call_splashscreen_1
  File "game/script.rpy", line 84, in script
    spouse "[player_name], I… I can’t. We can’t. I’m leaving you."
  File "/Users/gui/Desktop/renpy-6.99.5-sdk/renpy/ast.py", line 594, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "/Users/gui/Desktop/renpy-6.99.5-sdk/renpy/exports.py", line 1021, in say
    who(what, interact=interact)
  File "/Users/gui/Desktop/renpy-6.99.5-sdk/renpy/character.py", line 804, in __call__
    who = who_pattern.replace("[who]", sub(who))
  File "/Users/gui/Desktop/renpy-6.99.5-sdk/renpy/character.py", line 799, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/Users/gui/Desktop/renpy-6.99.5-sdk/renpy/substitutions.py", line 229, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 543, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 565, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 626, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in get_value
KeyError: 'spousename'

Darwin-14.4.0-x86_64-i386-64bit
Ren'Py 6.99.5.602
IMGD_Project 0.0
